const cacheName = 'herrscher-of-cache';

const cacheAssets = [
    'site.webmanifest',
    '/assets/img/bg.webp',
    // fonts
    'https://fonts.googleapis.com/icon?family=Material+Icons',
    'https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap',
    'https://fonts.gstatic.com/s/raleway/v27/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVtaorCIPrEVJz9d.woff2',
    'https://fonts.gstatic.com/s/materialicons/v129/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2',
    // html
    'index.html',
    'about.html',
    // javascript
    '/scripts/data.js',
    '/scripts/guide.js',
    '/scripts/build.js',
    '/scripts/main.js',
    // styles
    '/assets/styles/reset.css',
    '/assets/styles/styles.css',
    // favicon
    '/assets/favicon/favicon.ico',
    '/assets/favicon/android-chrome-192x192.png',
    '/assets/favicon/android-chrome-512x512.png',
    '/assets/favicon/favicon-16x16.png',
    '/assets/favicon/favicon-32x32.png',
    '/assets/favicon/maskable-icon.png',
    '/assets/favicon/mstile-150x150.png',
    '/assets/favicon/safari-pinned-tab.svg',
    // valks
    '/assets/img/valks/Argent_Knight_Artemis.webp',
    '/assets/img/valks/Bright_Knight_Excelsis.webp',
    '/assets/img/valks/Dea_Anchora.webp',
    '/assets/img/valks/Disciplinary_Perdition.webp',
    '/assets/img/valks/Fallen_Rosemary.webp',
    '/assets/img/valks/Fervent_Tempo.webp',
    '/assets/img/valks/Golden_Diva.webp',
    '/assets/img/valks/Goushinnso_Memento.webp',
    '/assets/img/valks/Helical_Contraption.webp',
    '/assets/img/valks/Herrscher_of_Flamescion.webp',
    '/assets/img/valks/Herrscher_of_Reason.webp',
    '/assets/img/valks/Herrscher_of_Sentience.webp',
    '/assets/img/valks/Herrscher_of_Thunder.webp',
    '/assets/img/valks/Infinite_Ouroboros.webp',
    '/assets/img/valks/Luna_Kindred.webp',
    '/assets/img/valks/Midnight_Absinthe.webp',
    '/assets/img/valks/Miss_Pink_Elf.webp',
    '/assets/img/valks/Palatinus_Equinox.webp',
    '/assets/img/valks/Prinzessin_der_Verurteilung.webp',
    '/assets/img/valks/Reverist_Calico.webp',
    '/assets/img/valks/Ritual_Imayoh.webp',
    '/assets/img/valks/Silverwing_N-EX.webp',
    '/assets/img/valks/Spina_Astera.webp',
    '/assets/img/valks/Starchasm_Nyx.webp',
    '/assets/img/valks/Starry_Impression.webp',
    '/assets/img/valks/Stygian_Nymph.webp',
    '/assets/img/valks/Striker_Fulminata.webp',
    '/assets/img/valks/Sweet_n_Spicy.webp',
    '/assets/img/valks/Twilight_Paladin.webp',
    '/assets/img/valks/Valkyrie_Gloria.webp',
    // avatars
    '/assets/img/avatars/Azure_Empyrea_Avatar.webp',
    '/assets/img/avatars/Blood_Rose_Avatar.webp',
    '/assets/img/avatars/Divine_Prayer_Avatar.webp',
    '/assets/img/avatars/Haxxor_Bunny_Avatar.webp',
    '/assets/img/avatars/Lightning_Empress_Avatar.webp',
    '/assets/img/avatars/Midnight_Absinthe_Avatar.webp',
    '/assets/img/avatars/Snowy_Sniper_Avatar.webp',
    '/assets/img/avatars/Starlit_Astrologos_Avatar.webp',
    '/assets/img/avatars/Stygian_Nymph_Avatar.webp',
    '/assets/img/avatars/Valkyrie_Chariot_Avatar.webp',
    // signets
    '/assets/img/signets/Aponia_Signet.webp',
    '/assets/img/signets/Eden_Signet.webp',
    '/assets/img/signets/Griseo_Signet.webp',
    '/assets/img/signets/Hua_Signet.webp',
    '/assets/img/signets/Kalpas_Signet.webp',
    '/assets/img/signets/Kevin_Signet.webp',
    '/assets/img/signets/Kosma_Signet.webp',
    '/assets/img/signets/Mobius_Signet.webp',
    '/assets/img/signets/Pardofelis_Signet.webp',
    '/assets/img/signets/Sakura_Signet.webp',
    '/assets/img/signets/Su_Signet.webp',
    '/assets/img/signets/Vill-V_Signet.webp',
    // emblems
    '/assets/img/emblems/Because_of_You.webp',
    '/assets/img/emblems/Boundless_Logos.webp',
    '/assets/img/emblems/Burden.webp',
    '/assets/img/emblems/Dreamful_Gold.webp',
    '/assets/img/emblems/Empty_Like_Shala.webp',
    '/assets/img/emblems/Falling_in_Past_Light.webp',
    '/assets/img/emblems/Faraway_Ship.webp',
    '/assets/img/emblems/Feast_of_Emptiness.webp',
    '/assets/img/emblems/Forbidden_Seed.webp',
    '/assets/img/emblems/Forget_Me_Not.webp',
    '/assets/img/emblems/Fragile_Friend.webp',
    '/assets/img/emblems/Gold_Goblet.webp',
    '/assets/img/emblems/Good_Old_Days.webp',
    '/assets/img/emblems/Grey_Scale_Rainbow.webp',
    '/assets/img/emblems/Heavy_as_a_Million_Lives.webp',
    '/assets/img/emblems/Home_Lost.webp',
    '/assets/img/emblems/Hometown.webp',
    '/assets/img/emblems/It_Will_Be_Written.webp',
    '/assets/img/emblems/Key_to_the_Deep.webp',
    '/assets/img/emblems/Light_as_a_Bodhi_Leaf.webp',
    '/assets/img/emblems/Mad_Kings_Mask.webp',
    '/assets/img/emblems/Memory.webp',
    '/assets/img/emblems/Out_of_Reach.webp',
    '/assets/img/emblems/Proof_of_Good_and_Evil.webp',
    '/assets/img/emblems/Pseudo_Miracle.webp',
    '/assets/img/emblems/Rainbow_of_Absence.webp',
    '/assets/img/emblems/Resolve.webp',
    '/assets/img/emblems/Ruined_Legacy.webp',
    '/assets/img/emblems/Stained_Sakura.webp',
    '/assets/img/emblems/The_Lonely_Moon.webp',
    '/assets/img/emblems/Thorny_Crown.webp',
    '/assets/img/emblems/Tin_Flask.webp',
    '/assets/img/emblems/Tsukimi_Himiko.webp',
    '/assets/img/emblems/Veil_of_Tears.webp',
    // stigmatas
    '/assets/img/stigmatas/Allan_Poe_T.webp',
    '/assets/img/stigmatas/Allan_Poe_M.webp',
    '/assets/img/stigmatas/Allan_Poe_B.webp',
    '/assets/img/stigmatas/Ana_Schariac_T.webp',
    '/assets/img/stigmatas/Ana_Schariac_M.webp',
    '/assets/img/stigmatas/Ana_Schariac_B.webp',
    '/assets/img/stigmatas/Aslaug_T.webp',
    '/assets/img/stigmatas/Aslaug_M.webp',
    '/assets/img/stigmatas/Aslaug_B.webp',
    '/assets/img/stigmatas/Bastet_T.webp',
    '/assets/img/stigmatas/Bastet_M.webp',
    '/assets/img/stigmatas/Bastet_B.webp',
    '/assets/img/stigmatas/Benares_Awakening_T.webp',
    '/assets/img/stigmatas/Benares_Awakening_M.webp',
    '/assets/img/stigmatas/Benares_Awakening_B.webp',
    '/assets/img/stigmatas/Bianka_Theatre_T.webp',
    '/assets/img/stigmatas/Bianka_Theatre_M.webp',
    '/assets/img/stigmatas/Bianka_Theatre_B.webp',
    '/assets/img/stigmatas/Bronya_N-EX_T.webp',
    '/assets/img/stigmatas/Bronya_N-EX_M.webp',
    '/assets/img/stigmatas/Bronya_N-EX_B.webp',
    '/assets/img/stigmatas/Carlo_Collodi_T.webp',
    '/assets/img/stigmatas/Carlo_Collodi_M.webp',
    '/assets/img/stigmatas/Carlo_Collodi_B.webp',
    '/assets/img/stigmatas/Cezanne_T.webp',
    '/assets/img/stigmatas/Cezanne_M.webp',
    '/assets/img/stigmatas/Cezanne_B.webp',
    '/assets/img/stigmatas/Dante_T.webp',
    '/assets/img/stigmatas/Dante_M.webp',
    '/assets/img/stigmatas/Dante_B.webp',
    '/assets/img/stigmatas/Dirac_T.webp',
    '/assets/img/stigmatas/Dirac_M.webp',
    '/assets/img/stigmatas/Dirac_B.webp',
    '/assets/img/stigmatas/Dracula_T.webp',
    '/assets/img/stigmatas/Dracula_M.webp',
    '/assets/img/stigmatas/Dracula_B.webp',
    '/assets/img/stigmatas/Elysia_T.webp',
    '/assets/img/stigmatas/Elysia_M.webp',
    '/assets/img/stigmatas/Elysia_B.webp',
    '/assets/img/stigmatas/Handel_T.webp',
    '/assets/img/stigmatas/Handel_M.webp',
    '/assets/img/stigmatas/Handel_B.webp',
    '/assets/img/stigmatas/Irene_Adler_T.webp',
    '/assets/img/stigmatas/Irene_Adler_M.webp',
    '/assets/img/stigmatas/Irene_Adler_B.webp',
    '/assets/img/stigmatas/Kafka_T.webp',
    '/assets/img/stigmatas/Kafka_M.webp',
    '/assets/img/stigmatas/Kafka_B.webp',
    '/assets/img/stigmatas/Leeuwenhoek_T.webp',
    '/assets/img/stigmatas/Leeuwenhoek_B.webp',
    '/assets/img/stigmatas/Linnaeus_T.webp',
    '/assets/img/stigmatas/Linnaeus_M.webp',
    '/assets/img/stigmatas/Linnaeus_B.webp',
    '/assets/img/stigmatas/Marco_Polo_M.webp',
    '/assets/img/stigmatas/Michelangelo_T.webp',
    '/assets/img/stigmatas/Michelangelo_B.webp',
    '/assets/img/stigmatas/Murata_Himeko_T.webp',
    '/assets/img/stigmatas/Murata_Himeko_M.webp',
    '/assets/img/stigmatas/Murata_Himeko_B.webp',
    '/assets/img/stigmatas/Paganini_T.webp',
    '/assets/img/stigmatas/Paganini_M.webp',
    '/assets/img/stigmatas/Paganini_B.webp',
    '/assets/img/stigmatas/Ragna_T.webp',
    '/assets/img/stigmatas/Ragna_M.webp',
    '/assets/img/stigmatas/Ragna_B.webp',
    '/assets/img/stigmatas/Mei_Spectramancer_T.webp',
    '/assets/img/stigmatas/Fu_Hua_Onyx_Simurgh_B.webp',
    '/assets/img/stigmatas/Robert_Peary_T.webp',
    '/assets/img/stigmatas/Robert_Peary_M.webp',
    '/assets/img/stigmatas/Robert_Peary_B.webp',
    '/assets/img/stigmatas/Shakespeare_Adrift_T.webp',
    '/assets/img/stigmatas/Shakespeare_Adrift_M.webp',
    '/assets/img/stigmatas/Shakespeare_Adrift_B.webp',
    '/assets/img/stigmatas/Raksha_T.webp',
    '/assets/img/stigmatas/Sushang_M.webp',
    '/assets/img/stigmatas/Empyrea_Phoenix_B.webp',
    '/assets/img/stigmatas/Siegfried_Kaslana_M.webp',
    '/assets/img/stigmatas/Thales_M.webp',
    '/assets/img/stigmatas/Verne_T.webp',
    '/assets/img/stigmatas/Verne_M.webp',
    '/assets/img/stigmatas/Verne_B.webp',
    '/assets/img/stigmatas/Wang_Zhenyi_T.webp',
    '/assets/img/stigmatas/Wang_Zhenyi_M.webp',
    '/assets/img/stigmatas/Wang_Zhenyi_B.webp',
    '/assets/img/stigmatas/Welt_Yang_T.webp',
    '/assets/img/stigmatas/Welt_Yang_M.webp',
    '/assets/img/stigmatas/Welt_Yang_B.webp',
    '/assets/img/stigmatas/Zeno_T.webp',
    '/assets/img/stigmatas/Zeno_M.webp',
    '/assets/img/stigmatas/Zeno_B.webp',
    '/assets/img/weapons/0_high_atk_weap.webp',
    '/assets/img/weapons/3rd_Sacred_Relic.webp',
    '/assets/img/weapons/Abyss_Flower_Liminal_Spiral.webp',
    '/assets/img/weapons/Astral_Divide_Pisces.webp',
    '/assets/img/weapons/Basilisks_Image_Deathshroud.webp',
    '/assets/img/weapons/Dawn_Breaker_Talwar.webp',
    '/assets/img/weapons/Domain_of_Incandescence.webp',
    '/assets/img/weapons/Domain_of_Revelation.webp',
    '/assets/img/weapons/Domain_of_Sanction.webp',
    '/assets/img/weapons/Domain_of_Sentience.webp',
    '/assets/img/weapons/Domain_of_the_Void.webp',
    '/assets/img/weapons/Echo_of_Paradise.webp',
    '/assets/img/weapons/Elysian_Astra_Hearts_Color.webp',
    '/assets/img/weapons/Eos_Gloria.webp',
    '/assets/img/weapons/Falcon_Flare_FINAL.webp',
    '/assets/img/weapons/Frozen_Naraka.webp',
    '/assets/img/weapons/Hekates_Sombre.webp',
    '/assets/img/weapons/Iris_of_Helheim.webp',
    '/assets/img/weapons/Lost_Conviction_Damnation.webp',
    '/assets/img/weapons/Midnight_Ataegina.webp',
    '/assets/img/weapons/Miracle_Kissy_Pillow.webp',
    '/assets/img/weapons/Mitternachts_Waltz.webp',
    '/assets/img/weapons/Muramasa_Bloodlust.webp',
    '/assets/img/weapons/Oblivion_Down.webp',
    '/assets/img/weapons/Obscuring_Wing.webp',
    '/assets/img/weapons/Path_to_Acheron_Kindred.webp',
    '/assets/img/weapons/Positron_Blasters.webp',
    '/assets/img/weapons/Purana_Phantasma.webp',
    '/assets/img/weapons/Sagittarius_Astra.webp',
    '/assets/img/weapons/Sanguine_Gaze_Union.webp',
    '/assets/img/weapons/Seven_Thunders_of_Retribution_Narukami.webp',
    '/assets/img/weapons/Seven_Thunders_of_Retribution_Rumble.webp',
    '/assets/img/weapons/Skadi_of_Thrymheim.webp',
    '/assets/img/weapons/Sleepers_Dream.webp',
    '/assets/img/weapons/Tower_of_the_Past_Silk_Ladder.webp',
    '/assets/img/weapons/Whisper_of_the_Past_Sonnet.webp'
]

// installation
self.addEventListener('install', (e) => {
    console.log('Service Worker: Installed');
    e.waitUntil(
        caches.open(cacheName)
            .then(cache => {
                console.log('Service Worker: Caching Files');
                cache.addAll(cacheAssets);
            })
            .then(() => self.skipWaiting())
    );
});

// activation
self.addEventListener('activate', () => {
    console.log('Service Worker: Installed');
});

// fetch
self.addEventListener('fetch', (e) => {
    console.log('Service Worker: Fetching');
    e.respondWith(fetch(e.request).catch(() => caches.match(e.request))); 
});