const cacheName = 'herrscher-of-cache';

const cachestatic = [
    './site.webmanifest',
    './static/img.webp',
    // fonts
    'https://fonts.googleapis.com/icon?family=Material+Icons',
    'https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap',
    'https://fonts.gstatic.com/s/raleway/v27/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVtaorCIPrEVJz9d.woff2',
    'https://fonts.gstatic.com/s/materialicons/v129/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2',
    // html
    './index.html',
    './about.html',
    // javascript
    './scripts/data.js',
    './scripts/guide.js',
    './scripts/build.js',
    './scripts/main.js',
    // styles
    './static/styles/reset.css',
    './static/styles/styles.css',
    // favicon
    './static/favicon/favicon.ico',
    './static/favicon/android-chrome-192x192.png',
    './static/favicon/android-chrome-512x512.png',
    './static/favicon/favicon-16x16.png',
    './static/favicon/favicon-32x32.png',
    './static/favicon/maskable-icon.png',
    './static/favicon/mstile-150x150.png',
    './static/favicon/safari-pinned-tab.svg',
    // valks
    './static/img/Argent_Knight_Artemis.webp',
    './static/img/Bright_Knight_Excelsis.webp',
    './static/img/Dea_Anchora.webp',
    './static/img/Disciplinary_Perdition.webp',
    './static/img/Fallen_Rosemary.webp',
    './static/img/Fervent_Tempo.webp',
    './static/img/Golden_Diva.webp',
    './static/img/Goushinnso_Memento.webp',
    './static/img/Helical_Contraption.webp',
    './static/img/Herrscher_of_Flamescion.webp',
    './static/img/Herrscher_of_Reason.webp',
    './static/img/Herrscher_of_Sentience.webp',
    './static/img/Herrscher_of_Thunder.webp',
    './static/img/Infinite_Ouroboros.webp',
    './static/img/Jade_Knight.webp',
    './static/img/Luna_Kindred.webp',
    './static/img/Midnight_Absinthe.webp',
    './static/img/Miss_Pink_Elf.webp',
    './static/img/Palatinus_Equinox.webp',
    './static/img/Prinzessin_der_Verurteilung.webp',
    './static/img/Reverist_Calico.webp',
    './static/img/Ritual_Imayoh.webp',
    './static/img/Silverwing_N-EX.webp',
    './static/img/Spina_Astera.webp',
    './static/img/Starchasm_Nyx.webp',
    './static/img/Starry_Impression.webp',
    './static/img/Stygian_Nymph.webp',
    './static/img/Striker_Fulminata.webp',
    './static/img/Sweet_n_Spicy.webp',
    './static/img/Twilight_Paladin.webp',
    './static/img/Valkyrie_Gloria.webp',
    // avatars
    './static/img/Azure_Empyrea_Avatar.webp',
    './static/img/Blood_Rose_Avatar.webp',
    './static/img/Divine_Prayer_Avatar.webp',
    './static/img/Haxxor_Bunny_Avatar.webp',
    './static/img/Lightning_Empress_Avatar.webp',
    './static/img/Midnight_Absinthe_Avatar.webp',
    './static/img/Snowy_Sniper_Avatar.webp',
    './static/img/Starlit_Astrologos_Avatar.webp',
    './static/img/Stygian_Nymph_Avatar.webp',
    './static/img/Valkyrie_Chariot_Avatar.webp',
    // signets
    './static/img/Aponia_Signet.webp',
    './static/img/Eden_Signet.webp',
    './static/img/Griseo_Signet.webp',
    './static/img/Hua_Signet.webp',
    './static/img/Kalpas_Signet.webp',
    './static/img/Kevin_Signet.webp',
    './static/img/Kosma_Signet.webp',
    './static/img/Mobius_Signet.webp',
    './static/img/Pardofelis_Signet.webp',
    './static/img/Sakura_Signet.webp',
    './static/img/Su_Signet.webp',
    './static/img/Vill-V_Signet.webp',
    // emblems
    './static/img/Because_of_You.webp',
    './static/img/Boundless_Feeling.webp',
    './static/img/Boundless_Logos.webp',
    './static/img/Burden.webp',
    './static/img/Dreamful_Gold.webp',
    './static/img/Empty_Like_Shala.webp',
    './static/img/Falling_in_Past_Light.webp',
    './static/img/Faraway_Ship.webp',
    './static/img/Feast_of_Emptiness.webp',
    './static/img/Forbidden_Seed.webp',
    './static/img/Forget_Me_Not.webp',
    './static/img/Fragile_Friend.webp',
    './static/img/Gold_Goblet.webp',
    './static/img/Good_Old_Days.webp',
    './static/img/Grey_Scale_Rainbow.webp',
    './static/img/Heavy_as_a_Million_Lives.webp',
    './static/img/Home_Lost.webp',
    './static/img/Hometown.webp',
    './static/img/It_Will_Be_Written.webp',
    './static/img/Key_to_the_Deep.webp',
    './static/img/Light_as_a_Bodhi_Leaf.webp',
    './static/img/Mad_Kings_Mask.webp',
    './static/img/Memory.webp',
    './static/img/Out_of_Reach.webp',
    './static/img/Proof_of_Good_and_Evil.webp',
    './static/img/Pseudo_Miracle.webp',
    './static/img/Rainbow_of_Absence.webp',
    './static/img/Resolve.webp',
    './static/img/Ruined_Legacy.webp',
    './static/img/Stained_Sakura.webp',
    './static/img/The_Lonely_Moon.webp',
    './static/img/Thorny_Crown.webp',
    './static/img/Tin_Flask.webp',
    './static/img/Tsukimi_Himiko.webp',
    './static/img/Veil_of_Tears.webp',
    // stigmatas
    './static/img/Allan_Poe_T.webp',
    './static/img/Allan_Poe_M.webp',
    './static/img/Allan_Poe_B.webp',
    './static/img/Ana_Schariac_T.webp',
    './static/img/Ana_Schariac_M.webp',
    './static/img/Ana_Schariac_B.webp',
    './static/img/Aslaug_T.webp',
    './static/img/Aslaug_M.webp',
    './static/img/Aslaug_B.webp',
    './static/img/Bastet_T.webp',
    './static/img/Bastet_M.webp',
    './static/img/Bastet_B.webp',
    './static/img/Benares_Awakening_T.webp',
    './static/img/Benares_Awakening_M.webp',
    './static/img/Benares_Awakening_B.webp',
    './static/img/Bianka_Theatre_T.webp',
    './static/img/Bianka_Theatre_M.webp',
    './static/img/Bianka_Theatre_B.webp',
    './static/img/Bronya_N-EX_T.webp',
    './static/img/Bronya_N-EX_M.webp',
    './static/img/Bronya_N-EX_B.webp',
    './static/img/Carlo_Collodi_T.webp',
    './static/img/Carlo_Collodi_M.webp',
    './static/img/Carlo_Collodi_B.webp',
    './static/img/Cezanne_T.webp',
    './static/img/Cezanne_M.webp',
    './static/img/Cezanne_B.webp',
    './static/img/Dante_T.webp',
    './static/img/Dante_M.webp',
    './static/img/Dante_B.webp',
    './static/img/Dirac_T.webp',
    './static/img/Dirac_M.webp',
    './static/img/Dirac_B.webp',
    './static/img/Dracula_T.webp',
    './static/img/Dracula_M.webp',
    './static/img/Dracula_B.webp',
    './static/img/Elysia_T.webp',
    './static/img/Elysia_M.webp',
    './static/img/Elysia_B.webp',
    './static/img/Elysia_Pristine_T.webp',
    './static/img/Elysia_Pristine_M.webp',
    './static/img/Elysia_Pristine_B.webp',
    './static/img/Handel_T.webp',
    './static/img/Handel_M.webp',
    './static/img/Handel_B.webp',
    './static/img/Irene_Adler_T.webp',
    './static/img/Irene_Adler_M.webp',
    './static/img/Irene_Adler_B.webp',
    './static/img/Kafka_T.webp',
    './static/img/Kafka_M.webp',
    './static/img/Kafka_B.webp',
    './static/img/Leeuwenhoek_T.webp',
    './static/img/Leeuwenhoek_B.webp',
    './static/img/Li_Sushang_Shenzhou_Reminiscence_T.webp',
    './static/img/Li_Sushang_Shenzhou_Reminiscence_M.webp',
    './static/img/Li_Sushang_Shenzhou_Reminiscence_B.webp',
    './static/img/Linnaeus_T.webp',
    './static/img/Linnaeus_M.webp',
    './static/img/Linnaeus_B.webp',
    './static/img/Marco_Polo_M.webp',
    './static/img/Michelangelo_T.webp',
    './static/img/Michelangelo_B.webp',
    './static/img/Murata_Himeko_T.webp',
    './static/img/Murata_Himeko_M.webp',
    './static/img/Murata_Himeko_B.webp',
    './static/img/Paganini_T.webp',
    './static/img/Paganini_M.webp',
    './static/img/Paganini_B.webp',
    './static/img/Ragna_T.webp',
    './static/img/Ragna_M.webp',
    './static/img/Ragna_B.webp',
    './static/img/Mei_Spectramancer_T.webp',
    './static/img/Fu_Hua_Onyx_Simurgh_B.webp',
    './static/img/Robert_Peary_T.webp',
    './static/img/Robert_Peary_M.webp',
    './static/img/Robert_Peary_B.webp',
    './static/img/Shakespeare_Adrift_T.webp',
    './static/img/Shakespeare_Adrift_M.webp',
    './static/img/Shakespeare_Adrift_B.webp',
    './static/img/Raksha_T.webp',
    './static/img/Sushang_M.webp',
    './static/img/Empyrea_Phoenix_B.webp',
    './static/img/Siegfried_Kaslana_M.webp',
    './static/img/Sirin_Ascendant_T.webp',
    './static/img/Sirin_Ascendant_M.webp',
    './static/img/Sirin_Ascendant_B.webp',
    './static/img/Thales_M.webp',
    './static/img/Verne_T.webp',
    './static/img/Verne_M.webp',
    './static/img/Verne_B.webp',
    './static/img/Wang_Zhenyi_T.webp',
    './static/img/Wang_Zhenyi_M.webp',
    './static/img/Wang_Zhenyi_B.webp',
    './static/img/Welt_Yang_T.webp',
    './static/img/Welt_Yang_M.webp',
    './static/img/Welt_Yang_B.webp',
    './static/img/Willows_T.webp',
    './static/img/Willows_M.webp',
    './static/img/Willows_B.webp',
    './static/img/Zeno_T.webp',
    './static/img/Zeno_M.webp',
    './static/img/Zeno_B.webp',
    // weapons
    './static/img/0_high_atk_weap.webp',
    './static/img/3rd_Sacred_Relic.webp',
    './static/img/Abyss_Flower_Liminal_Spiral.webp',
    './static/img/Astral_Divide_Pisces.webp',
    './static/img/Basilisks_Image_Deathshroud.webp',
    './static/img/Cosmic_Duality.webp',
    './static/img/Dawn_Breaker_Talwar.webp',
    './static/img/Domain_of_Ego_Flawless_Return.webp',
    './static/img/Domain_of_Incandescence.webp',
    './static/img/Domain_of_Revelation.webp',
    './static/img/Domain_of_Sanction.webp',
    './static/img/Domain_of_Sentience.webp',
    './static/img/Domain_of_the_Void.webp',
    './static/img/Echo_of_Paradise.webp',
    './static/img/Elysian_Astra_Hearts_Color.webp',
    './static/img/Eos_Gloria.webp',
    './static/img/Falcon_Flare_FINAL.webp',
    './static/img/Frozen_Naraka.webp',
    './static/img/Hekates_Sombre.webp',
    './static/img/Iris_of_Helheim.webp',
    './static/img/Keys_of_the_Void.webp',
    './static/img/Lost_Conviction_Damnation.webp',
    './static/img/Midnight_Ataegina.webp',
    './static/img/Midnight_Eclipse.webp',
    './static/img/Miracle_Kissy_Pillow.webp',
    './static/img/Mitternachts_Waltz.webp',
    './static/img/Muramasa_Bloodlust.webp',
    './static/img/Nocturnal_Stealth_Beam.webp',
    './static/img/Oblivion_Down.webp',
    './static/img/Obscuring_Wing.webp',
    './static/img/Path_to_Acheron_Kindred.webp',
    './static/img/Positron_Blasters.webp',
    './static/img/Purana_Phantasma.webp',
    './static/img/Sagittarius_Astra.webp',
    './static/img/Sanguine_Gaze_Union.webp',
    './static/img/Seven_Thunders_of_Retribution_Narukami.webp',
    './static/img/Seven_Thunders_of_Retribution_Rumble.webp',
    './static/img/Skadi_of_Thrymheim.webp',
    './static/img/Sleepers_Dream.webp',
    './static/img/Star_of_Eden_World.webp',
    './static/img/Tower_of_the_Past_Silk_Ladder.webp',
    './static/img/Whisper_of_the_Past_Sonnet.webp'
]

// installation
self.addEventListener('install', (e) => {
    console.log('Service Worker: Installed');
    e.waitUntil(
        caches.open(cacheName)
            .then(cache => {
                console.log('Service Worker: Caching Files');
                cache.addAll(cachestatic);
            })
            .then(() => self.skipWaiting())
    );
});

// activation
self.addEventListener('activate', () => {
    console.log('Service Worker: Installed');
});

// fetch
self.addEventListener('fetch', (e) => {
    console.log('Service Worker: Fetching');
    e.respondWith(fetch(e.request).catch(() => caches.match(e.request))); 
});