const cacheName = 'herrscher-of-cache';

const cacheAssets = [
    './site.webmanifest',
    './static/img/bg.png',
    // fonts
    'https://fonts.googleapis.com/icon?family=Material+Icons',
    'https://fonts.googleapis.com/css2?family=Raleway:wght@200&display=swap',
    'https://fonts.gstatic.com/s/raleway/v27/1Ptxg8zYS_SKggPN4iEgvnHyvveLxVtaorCIPrEVJz9d.woff2',
    'https://fonts.gstatic.com/s/materialicons/v129/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2',
    // html
    './index.html',
    './about.html',
    // javascript
    './static/script.js',
    // styles
    './static/styles/reset.css',
    './static/styles/styles.css',
    // favicon
    './static/favicon/favicon.ico',
    './static/favicon/android-chrome-192x192.png',
    './static/favicon/android-chrome-512x512.png',
    './static/favicon/favicon-16x16.png',
    './static/favicon/favicon-32x32.png',
    './static/favicon/maskable-icon.png',
    './static/favicon/mstile-150x150.png',
    './static/favicon/safari-pinned-tab.svg'
];

const images = [
    // valks (desktop)
    'Argent_Knight_Artemis_dt',
    'Bright_Knight_Excelsis_dt',
    'Dea_Anchora_dt',
    'Disciplinary_Perdition_dt',
    'Fallen_Rosemary_dt',
    'Fervent_Tempo_dt',
    'Golden_Diva_dt',
    'Goushinnso_Memento_dt',
    'Helical_Contraption_dt',
    'Herrscher_of_Flamescion_dt',
    'Herrscher_of_Reason_dt',
    'Herrscher_of_Sentience_dt',
    'Herrscher_of_Thunder_dt',
    'Infinite_Ouroboros_dt',
    'Jade_Knight_dt',
    'Luna_Kindred_dt',
    'Midnight_Absinthe_dt',
    'Miss_Pink_Elf_dt',
    'Palatinus_Equinox_dt',
    'Prinzessin_der_Verurteilung_dt',
    'Reverist_Calico_dt',
    'Ritual_Imayoh_dt',
    'Silverwing_N-EX_dt',
    'Spina_Astera_dt',
    'Starchasm_Nyx_dt',
    'Starry_Impression_dt',
    'Stygian_Nymph_dt',
    'Striker_Fulminata_dt',
    'Sweet_n_Spicy_dt',
    'Twilight_Paladin_dt',
    'Valkyrie_Gloria_dt',
    // valks (mobile)
    'Argent_Knight_Artemis_mb',
    'Bright_Knight_Excelsis_mb',
    'Dea_Anchora_mb',
    'Disciplinary_Perdition_mb',
    'Fallen_Rosemary_mb',
    'Fervent_Tempo_mb',
    'Golden_Diva_mb',
    'Goushinnso_Memento_mb',
    'Helical_Contraption_mb',
    'Herrscher_of_Flamescion_mb',
    'Herrscher_of_Reason_mb',
    'Herrscher_of_Sentience_mb',
    'Herrscher_of_Thunder_mb',
    'Infinite_Ouroboros_mb',
    'Jade_Knight_mb',
    'Luna_Kindred_mb',
    'Midnight_Absinthe_mb',
    'Miss_Pink_Elf_mb',
    'Palatinus_Equinox_mb',
    'Prinzessin_der_Verurteilung_mb',
    'Reverist_Calico_mb',
    'Ritual_Imayoh_mb',
    'Silverwing_N-EX_mb',
    'Spina_Astera_mb',
    'Starchasm_Nyx_mb',
    'Starry_Impression_mb',
    'Stygian_Nymph_mb',
    'Striker_Fulminata_mb',
    'Sweet_n_Spicy_mb',
    'Twilight_Paladin_mb',
    'Valkyrie_Gloria_mb',
    // avatars
    'Azure_Empyrea_Avatar',
    'Blood_Rose_Avatar',
    'Divine_Prayer_Avatar',
    'Haxxor_Bunny_Avatar',
    'Lightning_Empress_Avatar',
    'Midnight_Absinthe_Avatar',
    'Snowy_Sniper_Avatar',
    'Starlit_Astrologos_Avatar',
    'Stygian_Nymph_Avatar',
    'Valkyrie_Chariot_Avatar',
    // signets
    'Aponia_Signet',
    'Eden_Signet',
    'Griseo_Signet',
    'Hua_Signet',
    'Kalpas_Signet',
    'Kevin_Signet',
    'Kosma_Signet',
    'Mobius_Signet',
    'Pardofelis_Signet',
    'Sakura_Signet',
    'Su_Signet',
    'Vill-V_Signet',
    // emblems
    'Because_of_You',
    'Boundless_Feeling',
    'Boundless_Logos',
    'Burden',
    'Dreamful_Gold',
    'Empty_Like_Shala',
    'Falling_in_Past_Light',
    'Faraway_Ship',
    'Feast_of_Emptiness',
    'Forbidden_Seed',
    'Forget_Me_Not',
    'Fragile_Friend',
    'Gold_Goblet',
    'Good_Old_Days',
    'Grey_Scale_Rainbow',
    'Heavy_as_a_Million_Lives',
    'Home_Lost',
    'Hometown',
    'It_Will_Be_Written',
    'Key_to_the_Deep',
    'Light_as_a_Bodhi_Leaf',
    'Mad_Kings_Mask',
    'Memory',
    'Out_of_Reach',
    'Proof_of_Good_and_Evil',
    'Pseudo_Miracle',
    'Rainbow_of_Absence',
    'Resolve',
    'Ruined_Legacy',
    'Stained_Sakura',
    'The_Lonely_Moon',
    'Thorny_Crown',
    'Tin_Flask',
    'Tsukimi_Himiko',
    'Veil_of_Tears',
    // stigmatas
    'Allan_Poe_T',
    'Allan_Poe_M',
    'Allan_Poe_B',
    'Ana_Schariac_T',
    'Ana_Schariac_M',
    'Ana_Schariac_B',
    'Aslaug_T',
    'Aslaug_M',
    'Aslaug_B',
    'Bastet_T',
    'Bastet_M',
    'Bastet_B',
    'Benares_Awakening_T',
    'Benares_Awakening_M',
    'Benares_Awakening_B',
    'Bianka_Theatre_T',
    'Bianka_Theatre_M',
    'Bianka_Theatre_B',
    'Bronya_N-EX_T',
    'Bronya_N-EX_M',
    'Bronya_N-EX_B',
    'Carlo_Collodi_T',
    'Carlo_Collodi_M',
    'Carlo_Collodi_B',
    'Cezanne_T',
    'Cezanne_M',
    'Cezanne_B',
    'Dante_T',
    'Dante_M',
    'Dante_B',
    'Dirac_T',
    'Dirac_M',
    'Dirac_B',
    'Dracula_T',
    'Dracula_M',
    'Dracula_B',
    'Elysia_T',
    'Elysia_M',
    'Elysia_B',
    'Elysia_Pristine_T',
    'Elysia_Pristine_M',
    'Elysia_Pristine_B',
    'Handel_T',
    'Handel_M',
    'Handel_B',
    'Irene_Adler_T',
    'Irene_Adler_M',
    'Irene_Adler_B',
    'Kafka_T',
    'Kafka_M',
    'Kafka_B',
    'Leeuwenhoek_T',
    'Leeuwenhoek_B',
    'Li_Sushang_Shenzhou_Reminiscence_T',
    'Li_Sushang_Shenzhou_Reminiscence_M',
    'Li_Sushang_Shenzhou_Reminiscence_B',
    'Linnaeus_T',
    'Linnaeus_M',
    'Linnaeus_B',
    'Marco_Polo_M',
    'Michelangelo_T',
    'Michelangelo_B',
    'Murata_Himeko_T',
    'Murata_Himeko_M',
    'Murata_Himeko_B',
    'Paganini_T',
    'Paganini_M',
    'Paganini_B',
    'Ragna_T',
    'Ragna_M',
    'Ragna_B',
    'Mei_Spectramancer_T',
    'Fu_Hua_Onyx_Simurgh_B',
    'Robert_Peary_T',
    'Robert_Peary_M',
    'Robert_Peary_B',
    'Shakespeare_Adrift_T',
    'Shakespeare_Adrift_M',
    'Shakespeare_Adrift_B',
    'Raksha_T',
    'Sushang_M',
    'Empyrea_Phoenix_B',
    'Siegfried_Kaslana_M',
    'Sirin_Ascendant_T',
    'Sirin_Ascendant_M',
    'Sirin_Ascendant_B',
    'Thales_M',
    'Verne_T',
    'Verne_M',
    'Verne_B',
    'Wang_Zhenyi_T',
    'Wang_Zhenyi_M',
    'Wang_Zhenyi_B',
    'Welt_Yang_T',
    'Welt_Yang_M',
    'Welt_Yang_B',
    'Willows_T',
    'Willows_M',
    'Willows_B',
    'Zeno_T',
    'Zeno_M',
    'Zeno_B',
    // weapons
    '0_high_atk_weap',
    '3rd_Sacred_Relic',
    'Abyss_Flower_Liminal_Spiral',
    'Astral_Divide_Pisces',
    'Basilisks_Image_Deathshroud',
    'Cosmic_Duality',
    'Dawn_Breaker_Talwar',
    'Domain_of_Ego_Flawless_Return',
    'Domain_of_Incandescence',
    'Domain_of_Revelation',
    'Domain_of_Sanction',
    'Domain_of_Sentience',
    'Domain_of_the_Void',
    'Echo_of_Paradise',
    'Elysian_Astra_Hearts_Color',
    'Eos_Gloria',
    'Falcon_Flare_FINAL',
    'Frozen_Naraka',
    'Hekates_Sombre',
    'Iris_of_Helheim',
    'Keys_of_the_Void',
    'Lost_Conviction_Damnation',
    'Midnight_Ataegina',
    'Midnight_Eclipse',
    'Miracle_Kissy_Pillow',
    'Mitternachts_Waltz',
    'Muramasa_Bloodlust',
    'Nocturnal_Stealth_Beam',
    'Oblivion_Down',
    'Obscuring_Wing',
    'Path_to_Acheron_Kindred',
    'Positron_Blasters',
    'Purana_Phantasma',
    'Sagittarius_Astra',
    'Sanguine_Gaze_Union',
    'Seven_Thunders_of_Retribution_Narukami',
    'Seven_Thunders_of_Retribution_Rumble',
    'Skadi_of_Thrymheim',
    'Sleepers_Dream',
    'Star_of_Eden_World',
    'Tower_of_the_Past_Silk_Ladder',
    'Whisper_of_the_Past_Sonnet'
];

for (let i = 0; i < images.length; i++) {
    cacheAssets.push(`./static/img/${images[i]}.png`);
}

// installation
self.addEventListener('install', (e) => {
    console.log('Service Worker: Installed');
    e.waitUntil(
        caches.open(cacheName)
            .then(cache => {
                console.log('Service Worker: Caching Files');
                cache.addAll(cacheAssets);
            })
            .then(() => self.skipWaiting())
    );
});

// activation
self.addEventListener('activate', () => {
    console.log('Service Worker: Activated');
});

// fetch
self.addEventListener('fetch', (e) => {
    console.log('Service Worker: Fetching');
    e.respondWith(fetch(e.request).catch(() => caches.match(e.request))); 
});